### ISSUE TITLE
Link for PDF of the Color Images is not working.

### ISSUE THREAD

**Issue by paulpersad** [PacktPublishing/Blender-3D-By-Example-Second-Edition#3]
I am working through the book I purchased from Amazon.  Although the text and examples are good so far, the images are very difficult to see.  To be able to look at the pictures is necessary to complete the projects and the link given here on gitHub (same address as in the book) does not work.  This issue needs to be resolved.

**Comment by sarvesh-packt** [comment]
Hi @paulpersad 

We checked and found the link of the Color Images is working fine. If you still not able to open it you can check the README.md file from the Github repository and you can find the link to the color images there too. 

Also I'm posting the link for your reference you can check the following link.
https://static.packt-cdn.com/downloads/9781789612561_ColorImages.pdf

Regards,
